[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "cargo-zigbuild"
dependencies = ["ziglang>=0.9.0"]
dynamic = ["version"]

[tool.maturin]
bindings = "bin"
