name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci --omit=dev || npm i

      - name: Build (vite)
        run: |
          if [ -f package.json ] && jq -e '.scripts.build!=null' package.json >/dev/null 2>&1; then
            npm run build
          else
            npx vite build
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          branch: ${{ secrets.CLOUDFLARE_PAGES_BRANCH || 'main' }}
